import { Footer, Header } from '@components';
import './globals.css';
import type { Metadata } from 'next';

import localFont from 'next/font/local';

const pretendard = localFont({
  src: '../../public/font/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <Header />
        <Header.Margin />
        {children}
        <Footer />
      </body>
    </html>
  );
}
